FROM nginx:alpine

ENV RAILS_ROOT /app
WORKDIR $RAILS_ROOT

COPY docker/nginx.conf /tmp/docker.nginx

RUN envsubst "$RAILS_ROOT" < /tmp/docker.nginx > /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
