development:
  adapter: redis
  # url: <%= ENV.fetch("REDIS_URL") %>
  url: redis://localhost:6379/1

test:
  adapter: test

production:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") %>
  channel_prefix: rental_house_project_production
