default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  username: postgres
  password: 123456
  host: localhost
  port: 5432

development:
  <<: *default
  database: rental-house-database1

  username: postgres
  password: 123456
  host: localhost
  port: 5432

test:
  <<: *default
  database: rails_7_with_vite_template_test

production:
  <<: *default
  database: <%= ENV['RDS_DB_NAME'] %>
  username: <%= ENV['RDS_USERNAME'] %>
  password: <%= ENV['RDS_PASSWORD'] %>
  host: <%= ENV['RDS_HOSTNAME'] %>
  port: <%= ENV['RDS_PORT'] %>
